[package]
name = "skyfall_rs"
version = "0.1.0"
authors = ["h5p9sl <21267024+h5p9sl@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
backend = { path = "backend" }
piston = "0.49.0"
